"""add task_type to tasks

Revision ID: 25634cd70bd8
Revises: 1a37da820d50
Create Date: 2026-03-13 05:36:22.606681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25634cd70bd8'
down_revision: Union[str, None] = '1a37da820d50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('task_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'task_type')
    # ### end Alembic commands ###
