"""v182_shoot_date_datetime

Revision ID: 4c31bca5346b
Revises: ef0238d9fb79
Create Date: 2026-03-22 17:55:17.191146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c31bca5346b'
down_revision: Union[str, None] = 'ef0238d9fb79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shooting_briefs', 'shoot_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shooting_briefs', 'shoot_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###
